# Generated by Django 3.2.4 on 2021-06-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrokapoorapi', '0003_alter_categoryservice_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='astrokapoorapi.category'),
        ),
    ]
