# Generated by Django 3.2.4 on 2021-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrokapoorapi', '0004_auto_20210611_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryservice',
            name='Image',
            field=models.ImageField(upload_to='customerserviceimages/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Image',
            field=models.ImageField(upload_to='sellerimages/'),
        ),
    ]
