# Generated by Django 3.2.4 on 2021-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrokapoorapi', '0005_auto_20210611_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('Marital_Status', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'UnMarried')], max_length=15)),
                ('Date_of_birth', models.DateField()),
                ('Time', models.TimeField()),
                ('Country_of_birth', models.CharField(default='', max_length=100)),
                ('State_of_birth', models.CharField(default='', max_length=100)),
                ('Place_of_birth', models.CharField(default='', max_length=100)),
                ('Longitude', models.CharField(default='', max_length=100)),
                ('Latitude', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
