# Generated by Django 3.2.4 on 2021-06-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrokapoorapi', '0007_contactdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='Address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='Question',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
